

name: CI/CD Database

# Trigger workflow on push to main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: windows-latest
    environment: dev   # 👈 uses your dev environment and secrets

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Step 3: Build the database project (.dacpac)
    - name: Build Database Project
      run: msbuild DatabaseProjectrordb/DatabaseProjectrordb.sqlproj /t:Build /p:Configuration=Release

    # Step 4: Deploy .dacpac to SQL Server
    - name: Deploy DACPAC
      run: |
        sqlpackage /Action:Publish `
          /SourceFile:"$(Get-ChildItem -Path **\bin\Release\*.dacpac | Select-Object -First 1).FullName" `
          /TargetServerName:"${{ secrets.DB_SERVER }}" `
          /TargetDatabaseName:"${{ secrets.DB_NAME }}" `
          /TargetUser:"${{ secrets.DB_USER }}" `
          /TargetPassword:"${{ secrets.DB_PASSWORD }}"


